#!/usr/bin/env python
"""
FivcCliche CLI

Command-line interface for FivcCliche - a production-ready, multi-user backend
framework for AI agents built with FastAPI and SQLModel.
"""

import os
import shutil
from pathlib import Path
from typing import cast

import typer
from rich.console import Console
from rich.panel import Panel
from rich.text import Text

from fivcglue import query_component, IComponentSite
from fivccliche import __version__
from fivccliche.services.implements import service_site
from fivccliche.services.interfaces.modules import IModuleSite

cli = typer.Typer(
    name="FivcCliche",
    help="FivcCliche - Production-ready AI agent backend framework",
    rich_markup_mode="rich",
)

console = Console()

modules = query_component(cast(IComponentSite, service_site), IModuleSite)

# FastAPI App for ASGI
app = modules.create_application()


@cli.command()
def run(
    host: str = typer.Option("0.0.0.0", "--host", "-h", help="Host to bind the server to"),
    port: int = typer.Option(8000, "--port", "-p", help="Port to run the server on"),
    reload: bool = typer.Option(
        True, "--reload/--no-reload", help="Enable auto-reload on code changes"
    ),
    verbose: bool = typer.Option(False, "--verbose", "-v", help="Enable verbose output"),
    dry_run: bool = typer.Option(
        False, "--dry-run", help="Show what would be done without executing"
    ),
):
    """
    Run the FivcCliche FastAPI application
    """
    console.print(
        Panel.fit(
            Text("FivcCliche Server", style="bold blue"),
            subtitle="Production-ready AI agent backend",
        )
    )

    if dry_run:
        console.print("[yellow]DRY RUN:[/yellow] Would start FivcCliche server")
        console.print(f"[yellow]Host:[/yellow] {host}")
        console.print(f"[yellow]Port:[/yellow] {port}")
        console.print(f"[yellow]Reload:[/yellow] {reload}")
        return

    try:
        console.print(f"[blue]Starting server at http://{host}:{port}[/blue]")
        console.print("[yellow]Press Ctrl+C to stop the server[/yellow]")

        if verbose:
            console.print("[cyan]Verbose mode enabled[/cyan]")

        modules.run_application(app, host=host, port=port, reload=reload)

    except KeyboardInterrupt:
        console.print("\n[yellow]Server stopped by user[/yellow]")
    except Exception as e:
        console.print(f"[red]❌ Error running server: {e}[/red]")
        raise typer.Exit(1) from e


@cli.command()
def info():
    """
    Show information about FivcCliche
    """
    info_text = f"""
    [bold blue]FivcCliche[/bold blue] v{__version__}

    A production-ready, multi-user backend framework for AI agents.
    Built with FastAPI and SQLModel for high-performance, type-safe
    async operations that handle concurrent AI agent requests at scale.

    [bold]Features:[/bold]
    • Production-ready multi-user backend
    • Designed for AI agent interactions
    • Async architecture for concurrent request handling
    • Type-safe with Pydantic 2.0 validation
    • SQLModel ORM for reliable data persistence
    • Built on FastAPI for high performance
    • Modular architecture with component system

    [bold]Usage Examples:[/bold]
    fivccliche run                                    # Start server
    fivccliche run --port 9000                        # Custom port
    fivccliche run --host 127.0.0.1 --no-reload      # Production mode
    fivccliche info                                   # Show this information
    fivccliche clean                                  # Clean temporary files
    """

    console.print(Panel(info_text, title="FivcCliche", border_style="blue"))


@cli.command()
def clean():
    """
    Clean up temporary files and cache generated by FivcCliche
    """
    console.print("[yellow]Cleaning up temporary files...[/yellow]")

    try:
        # Define directories to clean
        cache_dirs = [
            ".pytest_cache",
            ".mypy_cache",
            ".ruff_cache",
            "__pycache__",
            ".coverage",
            "htmlcov",
        ]

        cleaned_count = 0

        for cache_dir in cache_dirs:
            cache_path = Path(cache_dir)
            if cache_path.exists():
                try:
                    if cache_path.is_dir():
                        shutil.rmtree(cache_path)
                    else:
                        cache_path.unlink()
                    console.print(f"[green]✅ Removed: {cache_dir}[/green]")
                    cleaned_count += 1
                except Exception as e:
                    console.print(f"[yellow]⚠️  Could not remove {cache_dir}: {e}[/yellow]")

        # Clean Python cache files
        for root, _dirs, files in os.walk("."):
            for file in files:
                if file.endswith(".pyc"):
                    try:
                        os.remove(os.path.join(root, file))
                        cleaned_count += 1
                    except Exception:
                        pass

        console.print("\n" + "=" * 60)
        console.print("[bold cyan]Cleanup Summary[/bold cyan]")
        console.print("=" * 60)
        console.print(f"[green]Items cleaned: {cleaned_count}[/green]")
        console.print("[green]✅ Cleanup completed successfully![/green]")

    except Exception as e:
        console.print(f"[red]❌ Error during cleanup: {e}[/red]")
        raise typer.Exit(1) from e


def main():
    """
    Main entry point for the CLI
    """
    cli()


if __name__ == "__main__":
    main()
